name: Upload to PyPI on Release

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write  # Needed for trusted publishing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install build tools
        run: |
          pip install --upgrade pip
          pip install build

      - name: Build the distribution
        run: python -m build

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
